dbt_transform:
  outputs:
    dev:
      dataset: namadataset
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /home/rismanovic/unit3/capstone-DE4_Alta_2/bigqueryKey.json
      location: EU
      method: service-account
      priority: interactive
      project: alta-de4-capstone-project
      threads: 1
      type: bigquery
  target: dev